replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []



nodeSelector: {}

tolerations: []

affinity: {}
